services:
  postgres-auth:
    image: postgres:14
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Majda2020
    ports:
      - "5433:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

  postgres-cabinet:
    image: postgres:14
    environment:
      POSTGRES_DB: cabinetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Majda2020
    ports:
      - "5434:5432"
    volumes:
      - postgres-cabinet-data:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - cabinet-service

  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_service

  cabinet-service:
    build: ./cabinet-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-cabinet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cabinet:5432/cabinetdb

volumes:
  postgres-auth-data:
  postgres-cabinet-data: