services:
  postgres-patients:
    image: postgres:17
    container_name: postgres-patients
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients
    ports:
      - "5433:5432"
    volumes:
      - patients_data:/var/lib/postgresql/data

volumes:
  patients_data: